OpenOrder/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import *
from userena import views as userena_views
from userena.views import *
import os

admin.autodiscover()

site_dir = os.path.dirname(settings.PROJECT_DIR)
doc_root = os.path.join(os.path.dirname(site_dir), 'docs/build/html')

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'OpenOrder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$',userena_views.signin,name='userena_signin'),
    url(r'^admin/doc/',        include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blogango.urls') ,name= 'blog'),
    url(r'^accounts/', include('userena.urls')),
    url(r'^message/', include('django_messages.urls')),
    url(r'^polls/', include('Order.urls' , namespace="polls")),
    url(r'^contact/', include('contact.urls' , namespace="contact")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
__author__ = 'HP'

from django.conf.urls import patterns, url

from Order import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
                       # ex: /polls/5/results/
                       url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
                       # ex: /polls/5/vote/
                       url(r'^(?P<poll_id>\d+)/vote/$', views.vote_view, name='vote'),
                       )

contact/urls.py
from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Django_Contact_Form.views.home', name='home'),
    # url(r'^Django_Contact_Form/', include('Django_Contact_Form.foo.urls')),
    url(r'^thankyou/', 'contact.controllers.thankyou' , name = 'thankyou'),
    url(r'^', 'contact.views.contact' , name= 'contact'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms 

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

contact/controllers.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def thankyou( request ):
   return render_to_response( 'contact/thankyou.html', { }, context_instance=RequestContext( request ) )

contact/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse

from contact.forms import *


def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST or None) # A form bound to the POST data
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = settings.RECIPIENTS
            if cc_myself:
                recipients.append(sender)

                send_mail(subject, message, sender, recipients)
                return HttpResponseRedirect(reverse('contact:thankyou')) # Redirect after POST # All validation rules pass
            # Process the data in form.cleaned_data
            # ...
            return HttpResponseRedirect(reverse('contact:thankyou'))# Redirect after POST
            # return HttpResponseRedirect('polls:results', args=(p.id,)))
    else:
        form = ContactForm() # An unbound form

    return render(request, 'contact/contact.html', {'form': form})

OpenOrder/templates/contact/contact.html
{% extends "base.html" %}

{% block content %}

<h1> Contact Us</h1>

<form action="/contact/" method="post">

{% csrf_token %}

<!--
** USE THIS METHOD IF YOU DONT WANT TO CHANGE THE FORM
{{ form.as_p }}

<input type="submit" value="Submit" />
</form>

-->

<p><label for="id_subject">Subject:</label>
    <input id="id_subject" type="text" name="subject" maxlength="100" /></p>

<p><label for="id_sender">Your email:</label>
    <input type="email"  name="sender" id="id_sender" /></p>

<p><label for="id_message">Message:</label>
    <textarea name="message" rows="8" cols="37"></textarea>

<p><label for="id_cc_myself">Cc myself:</label>
    <input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>

<input type="submit" value="Submit" />
</form>

{% if form.errors %} 
<p style="color: red;"> 
Please correct the error{{ form.errors|pluralize }} above. 
</p> 
{% endif %} 


{% endblock %}

OpenOrder/templates/contact/thankyou.html
{% extends "base.html" %}

{% block content %}

<h2>Thank you!</h2>

<p>Thank you for contacting us.</p>

<p>We will attempt to get back to you soon</p>


<a href="/"><button class="button">Go back to Website</button></a>


{% endblock %}