OpenOrder/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import *
from userena import views as userena_views
from userena.views import *
import os

admin.autodiscover()

site_dir = os.path.dirname(settings.PROJECT_DIR)
doc_root = os.path.join(os.path.dirname(site_dir), 'docs/build/html')

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'OpenOrder.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$',userena_views.signin,name='userena_signin'),
    url(r'^admin/doc/',        include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blogango.urls') ,name= 'blog'),
    url(r'^accounts/', include('userena.urls')),
    url(r'^message/', include('django_messages.urls')),
    url(r'^polls/', include('Order.urls' , namespace="polls")),
    url(r'^contact/', include('contact.urls' , namespace="contact")),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
__author__ = 'HP'

from django.conf.urls import patterns, url

from Order import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
                       # ex: /polls/5/results/
                       url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
                       # ex: /polls/5/vote/
                       url(r'^(?P<poll_id>\d+)/vote/$', views.vote_view, name='vote'),
                       )

contact/urls.py
from django.conf.urls import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Django_Contact_Form.views.home', name='home'),
    # url(r'^Django_Contact_Form/', include('Django_Contact_Form.foo.urls')),
    url(r'^thankyou/', 'contact.controllers.thankyou' , name = 'thankyou'),
    url(r'^', 'contact.views.contact' , name= 'contact'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

Order/models.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from userena.models import UserenaBaseProfile
from django.db import models
from django.contrib import admin
from django.utils import timezone
import datetime
from django.db import models
from django.contrib.auth.models import User
import hashlib


class MyProfile(UserenaBaseProfile):
    user = models.OneToOneField(User,
                                unique=True,
                                verbose_name=_('user'),
                                related_name='my_profile')
    favourite_snack = models.CharField(_('favourite snack'),
                                       max_length=5)

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    poll_section = (
        ('Sport', 'Sport'),
        ('Animation', 'Animation'),
        ('Health', 'Health'),
        ('Business', 'Business'),
        ('Lifestyle','Lifestyle'),
        )
    poll__section = models.CharField(max_length=60, choices=poll_section)



    def was__published__recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now

    was__published__recently.boolean = True

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.text

class Voter(models.Model):
    user = models.ForeignKey(User)
    poll = models.ForeignKey(Poll)

OpenOrder/templates/polls/base_generic.html
{% load url from future %}
{% load staticfiles %}
{% load i18n %}
<html lang="en">
  <head>
   
    <meta charset="utf-8">
    <title>Project Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
  <script src="{% static 'order/js/jquery.min.js'%}"></script>
  <script src="{% static 'order/js/bootstrap.min.js'%}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'order/css/bootstrap.min.css'%}">
       <link rel="stylesheet/less" href="{% static 'style.less'%}">
    <script src="{% static 'less.js'%}"></script>
  </head>
     <body data-offset="40">
<div class="container">
<header class="header">
<div class="row">
	<h1 class="span6"><a href="/" title="GheekLife"><img src="{% static 'order/img/7.png'%}" alt="GheekLife"/></a></h1>
	<div class="span6"><div class="pull-right"><br/> <a class="pull-right" href="mailto:lordsurh@gmail.com"><small> Email: lordsurh@gmail.com</small></a><strong><small> <br/>Call (24/7) :  ***********</small></strong></div></div>
</div>
</header>
    <div class="navbar">
  <div class="navbar-inner">
	<div class="container">
	  <div class="nav-collapse">
		<ul class="nav">
            <li class=""><a href="{% url 'userena_signin'  %}">Home</a></li>
			<li class="active"><a href="{% url 'polls:index' %}">Poll Application</a></li>
            <li class=""><a href="{% url 'blogango_index' %}">Blog Application</a></li>
			<li class=""><a href="{% url 'userena_profile_detail' user.username %}">View Profile</a></li>
            <li class="dropdown">
				<a data-toggle="dropdown" class="dropdown-toggle" href="#">Edit Profile<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li class="nav-header">Profile actions</li>
					<li><a href="{% url 'userena_profile_edit' user.username %}">Edit Details</a></li>
					<li><a href="{% url 'userena_password_change' user.username %}">Change Password</a></li>
					<li><a href="{% url 'userena_email_change' user.username %}">Change Email</a></li>
					<li class="divider"></li>
					<li><a href="{% url 'userena_signout'  %}">Signout</a></li>
				</ul>
			</li>
            <li class=""><a href="{% url 'contact:contact' %}">Contact Us</a></li>
		</ul>
		<ul class="nav pull-right">
		<li class="dropdown">
		  <a data-toggle="dropdown" class="dropdown-toggle" href="#"><img src="{% static 'order/img/en.png'%}" alt="English British"/> English<b class="caret"></b></a>
		  <ul class="dropdown-menu">
			  <li><a href="#"><img src="{% static 'order/img/en.png'%}"" alt="English British"/> English </a></li>
			  <li><a href="#"><img src="{% static 'order/img/fr.png'%}" alt="French"/> French</a></li>
			  <li><a href="#"><img src="{% static 'order/img/es.png'%}" alt="Spanish"/> Spanish</a></li>
			  <li><a href="#"><img src="{% static 'order/img/de.png'%}" alt="German"/> Germal</a></li>
		  </ul>
		  </li>
		</ul>
	  </div><!-- /.nav-collapse -->
	</div>
 </div><!-- /navbar-inner -->
    <div class="container theme-showcase">
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->

    
</body>
</html>

OpenOrder/templates/polls/detail.html
{% extends "polls/base_generic.html" %}
{% block content %}
     <div class="container">
<div class="row">
<div class="span6">
<ul class="breadcrumb">
  <li>
    <a href="{% url 'polls:index'%}">All Polls</a> <span class="divider">></span>
  </li>
  <li class="active">Vote Box</li>
     <li><span class="divider">></span>
    <a href="{% url 'polls:results' poll.id %}">Results</a>
  </li>

</ul>
</div>
</div>
</div>
<div class="row">

	{% if poll %}
		<div class="page-header">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <h2 class="">{{poll.question}}</h2>
       <H5> SECTION = {{ poll.poll__section }}</H5>
        </div>
    	<form action="{% url 'polls:vote' poll.id %}" method="post">
		{% csrf_token %}
        <div class="form-group">
  		{% for choice in poll.choice_set.all %}
 
    		<div class="radio" >
  			<label >
    		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
			 {{ choice.text }}
       		</label>
			</div> 
		{% endfor %}
        </div>
        
    	<div class="form-group " style="margin-top:10px">
      	<button type="submit" class="btn btn-default">Submit</button>
    
 		</div>
		</form>
		</div>
 	{% else %}
   			 <p>No info about this poll</p>
	{% endif %}
</div>
{% endblock %}

OpenOrder/templates/polls/index.html
{% extends "polls/base_generic.html" %}
{% load i18n %}
{% block content %}
    {% if error_message %}<strong> HI , {{ user }} {{ error_message }}</strong>
             {% else %}
              HI , {{ user }}
             {% endif %}


<div class="row">
		{% if latest_poll_list %}
    			<div class="page-header"> <h2> Latest Polls </h2></div>

    		<ul>

    			{% for poll in latest_poll_list %}
        		<li><a href="/polls/{{ poll.id }}/"> {{ poll.question }} </a></li>
    			{% endfor %}
   			 </ul>
		{% else %}
   			 <p>No polls are available.</p>
		{% endif %}
 </div>
    </div>
{%endblock%}

OpenOrder/templates/polls/results.html
{% load staticfiles %}
{% load url from future %}
<html lang="en">
  <head>
 <script src="{% static 'order/js/jquery.min.js'%}"></script>
  <script src="{% static 'order/js/bootstrap.min.js'%}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'order/css/bootstrap.min.css'%}">
       <link rel="stylesheet/less" href="{% static 'style.less'%}">
    <script src="{% static 'less.js'%}"></script>
   <script type="text/javascript" src="https://www.google.com/jsapi"></script>
   <script type="text/javascript">
     var data;
     var chart;
     // Load the Visualization API and the piechart package.
     google.load('visualization', '1', {'packages':['corechart']});
     // Set a callback to run when the Google Visualization API is loaded.
     google.setOnLoadCallback(drawChart);

     // Callback that creates and populates a data table,
     // instantiates the pie chart, passes in the data and
     // draws it.
     function drawChart() {

     // Create our data table.
     data = new google.visualization.DataTable();
     data.addColumn('string', 'Choice');
     data.addColumn('number', 'Votes');
     data.addRows([
     {% for choice in poll.choice_set.all %}
    ['{{ choice.text }}',{{ choice.votes }}]{% if not forloop.last %},{% endif %}
{% endfor %}]);

     // Set chart options
     var options = {'title':'Poll Results',
                       'width':400,
                       'height':300};

     // Instantiate and draw our chart, passing in some options.
     chart = new google.visualization.PieChart(document.getElementById('chart_div'));
     google.visualization.events.addListener(chart, 'select', selectHandler);
        chart.draw(data, options);
     }

      function selectHandler() {
        var selectedItem = chart.getSelection()[0];
        var value = data.getValue(selectedItem.row, 0);
        alert('The user selected ' + value);
      }

    </script> 
    
    <meta charset="utf-8">
    <title>Project Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    </head>
     <body data-offset="40">
<div class="container">
<header class="header">
<div class="row">
	<h1 class="span6"><a href="/" title="GheekLife"><img src="{% static 'order/img/7.png'%}" alt="GheekLife"/></a></h1>
	<div class="span6"><div class="pull-right"><br/> <a class="pull-right" href="mailto:lordsurh@gmail.com"><small> Email: lordsurh@gmail.com</small></a><strong><small> <br/>Call (24/7) :  ***********</small></strong></div></div>
</div>
</header>
    <div class="navbar">
  <div class="navbar-inner">
	<div class="container">
	  <div class="nav-collapse">
		<ul class="nav">
            <li class=""><a href="{% url 'userena_signin'  %}">Home</a></li>
			<li class=""><a href="{% url 'polls:index' %}">Poll Application</a></li>
			<li class=""><a href="{% url 'userena_profile_detail' user.username %}">View Profile</a></li>
            <li class="dropdown">
				<a data-toggle="dropdown" class="dropdown-toggle" href="#">Edit Profile<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li class="nav-header">Profile actions</li>
					<li><a href="{% url 'userena_profile_edit' user.username %}">Edit Details</a></li>
					<li><a href="{% url 'userena_password_change' user.username %}">Change Password</a></li>
					<li><a href="{% url 'userena_email_change' user.username %}">Change Email</a></li>
					<li class="divider"></li>
					<li><a href="{% url 'userena_signout'  %}">Signout</a></li>
				</ul>
			</li>
		</ul>
		<ul class="nav pull-right">
		<li class="dropdown">
		  <a data-toggle="dropdown" class="dropdown-toggle" href="#"><img src="{% static 'order/img/en.png'%}" alt="English British"/> English<b class="caret"></b></a>
		  <ul class="dropdown-menu">
			  <li><a href="#"><img src="{% static 'order/img/en.png'%}"" alt="English British"/> English </a></li>
			  <li><a href="#"><img src="{% static 'order/img/fr.png'%}" alt="French"/> French</a></li>
			  <li><a href="#"><img src="{% static 'order/img/es.png'%}" alt="Spanish"/> Spanish</a></li>
			  <li><a href="#"><img src="{% static 'order/img/de.png'%}" alt="German"/> Germal</a></li>
		  </ul>
		  </li>
		</ul>
	  </div><!-- /.nav-collapse -->
	</div>
 </div><!-- /navbar-inner -->
    <div class="container theme-showcase">
    <div class="container">
<div class="row">
<div class="span6">
<ul class="breadcrumb">
  <li>
    <a href="{% url 'polls:index'%}">All Polls</a> <span class="divider">></span>
  </li>
  <li>
    <a href="{% url 'polls:detail' poll.id %}">Vote Box</a> <span class="divider">></span>
  </li>
  <li class="active">Result</li>
</ul>
</div>
</div>
</div>
<h1>{{ poll.question }}</h1>
<div class="row">
<div style="margin-top:15px" class="col-sm-4 col-md-4 col-lg-4">
<ul>
<h4> What people voted: </h4>
<div style="margin-left:20px">
{% for choice in poll.choice_set.all %}
    <li><b>{{ choice.text }}</b>: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</div>
</ul>
</div>
<div class="col-sl-4 col-md-4 col-lg-4">
 <div id="chart_div" style="width:400; height:300"></div>
 </div>
  </div>
  </div> <!-- /container -->
    
    
</body>
</html>